### ISSUE TITLE
Blender 2.7 bug in toolpath

### ISSUE THREAD

**Issue by TurBoss** [vilemnovak/blendercam#41]
Hi i found a strange bug using blender 2.77 in tool path generation ( i know 2.77 not supported yet)
 better a pic

![captura de pantalla de 2016-04-02 00-54-18](https://cloud.githubusercontent.com/assets/184088/14222203/13a19d46-f86e-11e5-8f87-53352aa48a9f.png)

thx!

**Comment by TurBoss** [comment]
here is the blend file if is useful 
https://drive.google.com/file/d/0B2zAzLRUwfiNNkJ3YmlLRy1JMFE/view?usp=sharing

**Comment by nfz** [comment]
I'm using 2.77.  Will test your blend.

**Comment by nfz** [comment]
Ok, confirmed.  This is actually an old problem I thought was fixed but obviously not.  When exact mode is enabled the Bullet physics engine is used for detecting collisions between the tool and the surface.  The problem is at startup the Bullet physics engine sets a default collision shape (a capsule) that should have been deleted or moved out of the way, which is what you are seeing in the generated tool path.

  The work around (until this bug is fixed) is to turn off "Use exact mode" in the Cam optimization panel.  This will use a height map image instead which will be much faster too in generating the tool path.

**Comment by TurBoss** [comment]
thank you so much for your help :)

**Comment by TurBoss** [comment]
also I cange the machine geometry to be under zero in x and y so if you moved de default shape arround I found it heheheh

**Comment by vilemnovak** [comment]
Just fixed this, thanks for report!
It was an issue with scaling, the object was 100 meters away to not interfere, but I forgot that the whole scene gets scaled for simulation 100000 times, so those 100 meters made the cutter object being 1 cm from center :)

**Comment by TurBoss** [comment]
thank you
